### ISSUE TITLE
Sorting by RM does not work

### ISSUE THREAD

**Issue by sjcruiser** [doublechiang/UUT_Status#16]
"RM IP" sort does not seem to work.   
![image](https://user-images.githubusercontent.com/54157719/150428334-662c5a1a-13bb-4fe8-ba91-25cd5036808f.png)

**Comment by doublechiang** [comment]
sorting by RM IP? this is known issue, thank you for the report.

**Comment by doublechiang** [comment]
Thank you for your report. This feature is no longer required since we use the search result as our service.
